export interface District {
  id: string;
  name: string;
}

export interface Province {
  id: string;
  name: string;
  districts: District[];
}

export const VIETNAM_LOCATIONS: Province[] = [
  {
    id: "an-giang",
    name: "An Giang",
    districts: [
      { id: "long-xuyen", name: "Thành phố Long Xuyên" },
      { id: "chau-doc", name: "Thành phố Châu Đốc" },
      { id: "tan-chau", name: "Thị xã Tân Châu" },
      { id: "cho-moi", name: "Huyện Chợ Mới" },
      { id: "thoai-son", name: "Huyện Thoại Sơn" },
      { id: "tinh-bien", name: "Thị xã Tịnh Biên" },
    ],
  },
  {
    id: "ba-ria-vung-tau",
    name: "Bà Rịa - Vũng Tàu",
    districts: [
      { id: "vung-tau", name: "Thành phố Vũng Tàu" },
      { id: "ba-ria", name: "Thành phố Bà Rịa" },
      { id: "phu-my", name: "Thị xã Phú Mỹ" },
      { id: "long-dien", name: "Huyện Long Điền" },
      { id: "dat-do", name: "Huyện Đất Đỏ" },
      { id: "con-dao", name: "Huyện Côn Đảo" },
    ],
  },
  {
    id: "bac-giang",
    name: "Bắc Giang",
    districts: [
      { id: "bac-giang-city", name: "Thành phố Bắc Giang" },
      { id: "viet-yen", name: "Thị xã Việt Yên" },
      { id: "hiep-hoa", name: "Huyện Hiệp Hòa" },
      { id: "luc-ngan", name: "Huyện Lục Ngạn" },
      { id: "lang-giang", name: "Huyện Lạng Giang" },
      { id: "yen-dung", name: "Huyện Yên Dũng" },
    ],
  },
  {
    id: "bac-kan",
    name: "Bắc Kạn",
    districts: [
      { id: "bac-kan-city", name: "Thành phố Bắc Kạn" },
      { id: "ba-be", name: "Huyện Ba Bể" },
      { id: "cho-don", name: "Huyện Chợ Đồn" },
      { id: "na-ri", name: "Huyện Na Rì" },
      { id: "bach-thong", name: "Huyện Bạch Thông" },
    ],
  },
  {
    id: "bac-lieu",
    name: "Bạc Liêu",
    districts: [
      { id: "bac-lieu-city", name: "Thành phố Bạc Liêu" },
      { id: "gia-rai", name: "Thị xã Giá Rai" },
      { id: "hoa-binh", name: "Huyện Hòa Bình" },
      { id: "dong-hai", name: "Huyện Đông Hải" },
      { id: "vinh-loi", name: "Huyện Vĩnh Lợi" },
    ],
  },
  {
    id: "bac-ninh",
    name: "Bắc Ninh",
    districts: [
      { id: "bac-ninh-city", name: "Thành phố Bắc Ninh" },
      { id: "tu-son", name: "Thành phố Từ Sơn" },
      { id: "thuan-thanh", name: "Thị xã Thuận Thành" },
      { id: "que-vo", name: "Thị xã Quế Võ" },
      { id: "yen-phong", name: "Huyện Yên Phong" },
      { id: "tien-du", name: "Huyện Tiên Du" },
    ],
  },
  {
    id: "ben-tre",
    name: "Bến Tre",
    districts: [
      { id: "ben-tre-city", name: "Thành phố Bến Tre" },
      { id: "chau-thanh-bt", name: "Huyện Châu Thành" },
      { id: "cho-lach", name: "Huyện Chợ Lách" },
      { id: "mo-cay-nam", name: "Huyện Mỏ Cày Nam" },
      { id: "ba-tri", name: "Huyện Ba Tri" },
      { id: "binh-dai", name: "Huyện Bình Đại" },
    ],
  },
  {
    id: "binh-dinh",
    name: "Bình Định",
    districts: [
      { id: "quy-nhon", name: "Thành phố Quy Nhơn" },
      { id: "an-nhon", name: "Thị xã An Nhơn" },
      { id: "hoai-nhon", name: "Thị xã Hoài Nhơn" },
      { id: "tuy-phuoc", name: "Huyện Tuy Phước" },
      { id: "tay-son", name: "Huyện Tây Sơn" },
      { id: "phu-my-bd", name: "Huyện Phù Mỹ" },
    ],
  },
  {
    id: "binh-duong",
    name: "Bình Dương",
    districts: [
      { id: "thu-dau-mot", name: "Thành phố Thủ Dầu Một" },
      { id: "thuan-an", name: "Thành phố Thuận An" },
      { id: "di-an", name: "Thành phố Dĩ An" },
      { id: "tan-uyen", name: "Thành phố Tân Uyên" },
      { id: "ben-cat", name: "Thành phố Bến Cát" },
      { id: "dau-tieng", name: "Huyện Dầu Tiếng" },
    ],
  },
  {
    id: "binh-phuoc",
    name: "Bình Phước",
    districts: [
      { id: "dong-xoai", name: "Thành phố Đồng Xoài" },
      { id: "phuoc-long", name: "Thị xã Phước Long" },
      { id: "binh-long", name: "Thị xã Bình Long" },
      { id: "chon-thanh", name: "Thị xã Chơn Thành" },
      { id: "dong-phu", name: "Huyện Đồng Phú" },
    ],
  },
  {
    id: "binh-thuan",
    name: "Bình Thuận",
    districts: [
      { id: "phan-thiet", name: "Thành phố Phan Thiết" },
      { id: "la-gi", name: "Thị xã La Gi" },
      { id: "tuy-phong", name: "Huyện Tuy Phong" },
      { id: "bac-binh", name: "Huyện Bắc Bình" },
      { id: "ham-thuan-bac", name: "Huyện Hàm Thuận Bắc" },
      { id: "phu-quy", name: "Huyện Phú Quý" },
    ],
  },
  {
    id: "ca-mau",
    name: "Cà Mau",
    districts: [
      { id: "ca-mau-city", name: "Thành phố Cà Mau" },
      { id: "nam-can", name: "Huyện Năm Căn" },
      { id: "tran-van-thoi", name: "Huyện Trần Văn Thời" },
      { id: "dam-doi", name: "Huyện Đầm Dơi" },
      { id: "cai-nuoc", name: "Huyện Cái Nước" },
    ],
  },
  {
    id: "can-tho",
    name: "Cần Thơ",
    districts: [
      { id: "ninh-kieu", name: "Quận Ninh Kiều" },
      { id: "cai-rang", name: "Quận Cái Răng" },
      { id: "binh-thuy", name: "Quận Bình Thủy" },
      { id: "o-mon", name: "Quận Ô Môn" },
      { id: "thot-not", name: "Quận Thốt Nốt" },
      { id: "phong-dien", name: "Huyện Phong Điền" },
    ],
  },
  {
    id: "cao-bang",
    name: "Cao Bằng",
    districts: [
      { id: "cao-bang-city", name: "Thành phố Cao Bằng" },
      { id: "trung-khanh", name: "Huyện Trùng Khánh" },
      { id: "quang-hoa", name: "Huyện Quảng Hòa" },
      { id: "thach-an", name: "Huyện Thạch An" },
      { id: "bao-lac", name: "Huyện Bảo Lạc" },
    ],
  },
  {
    id: "da-nang",
    name: "Đà Nẵng",
    districts: [
      { id: "hai-chau", name: "Quận Hải Châu" },
      { id: "thanh-khe", name: "Quận Thanh Khê" },
      { id: "son-tra", name: "Quận Sơn Trà" },
      { id: "ngu-hanh-son", name: "Quận Ngũ Hành Sơn" },
      { id: "lien-chieu", name: "Quận Liên Chiểu" },
      { id: "cam-le", name: "Quận Cẩm Lệ" },
      { id: "hoa-vang", name: "Huyện Hòa Vang" },
    ],
  },
  {
    id: "dak-lak",
    name: "Đắk Lắk",
    districts: [
      { id: "buon-ma-thuot", name: "Thành phố Buôn Ma Thuột" },
      { id: "buon-ho", name: "Thị xã Buôn Hồ" },
      { id: "krong-pac", name: "Huyện Krông Pắc" },
      { id: "ea-hleo", name: "Huyện Ea H'leo" },
      { id: "krong-ana", name: "Huyện Krông Ana" },
      { id: "cu-mgar", name: "Huyện Cư M'gar" },
    ],
  },
  {
    id: "dak-nong",
    name: "Đắk Nông",
    districts: [
      { id: "gia-nghia", name: "Thành phố Gia Nghĩa" },
      { id: "dak-mil", name: "Huyện Đắk Mil" },
      { id: "cu-jut", name: "Huyện Cư Jút" },
      { id: "dak-rlap", name: "Huyện Đắk R'lấp" },
      { id: "krong-no", name: "Huyện Krông Nô" },
    ],
  },
  {
    id: "dien-bien",
    name: "Điện Biên",
    districts: [
      { id: "dien-bien-phu", name: "Thành phố Điện Biên Phủ" },
      { id: "muong-lay", name: "Thị xã Mường Lay" },
      { id: "dien-bien-dist", name: "Huyện Điện Biên" },
      { id: "tuan-giao", name: "Huyện Tuần Giáo" },
      { id: "muong-nhe", name: "Huyện Mường Nhé" },
    ],
  },
  {
    id: "dong-nai",
    name: "Đồng Nai",
    districts: [
      { id: "bien-hoa", name: "Thành phố Biên Hòa" },
      { id: "long-khanh", name: "Thành phố Long Khánh" },
      { id: "nhon-trach", name: "Huyện Nhơn Trạch" },
      { id: "trang-bom", name: "Huyện Trảng Bom" },
      { id: "long-thanh", name: "Huyện Long Thành" },
      { id: "vinh-cuu", name: "Huyện Vĩnh Cửu" },
    ],
  },
  {
    id: "dong-thap",
    name: "Đồng Tháp",
    districts: [
      { id: "cao-lanh", name: "Thành phố Cao Lãnh" },
      { id: "sa-dec", name: "Thành phố Sa Đéc" },
      { id: "hong-ngu-city", name: "Thành phố Hồng Ngự" },
      { id: "lap-vo", name: "Huyện Lấp Vò" },
      { id: "thanh-binh", name: "Huyện Thanh Bình" },
      { id: "thap-muoi", name: "Huyện Tháp Mười" },
    ],
  },
  {
    id: "gia-lai",
    name: "Gia Lai",
    districts: [
      { id: "pleiku", name: "Thành phố Pleiku" },
      { id: "an-khe", name: "Thị xã An Khê" },
      { id: "ayun-pa", name: "Thị xã Ayun Pa" },
      { id: "chu-se", name: "Huyện Chư Sê" },
      { id: "chu-prong", name: "Huyện Chư Prông" },
    ],
  },
  {
    id: "ha-giang",
    name: "Hà Giang",
    districts: [
      { id: "ha-giang-city", name: "Thành phố Hà Giang" },
      { id: "dong-van", name: "Huyện Đồng Văn" },
      { id: "meo-vac", name: "Huyện Mèo Vạc" },
      { id: "bac-me", name: "Huyện Bắc Mê" },
      { id: "vi-xuyen", name: "Huyện Vị Xuyên" },
    ],
  },
  {
    id: "ha-nam",
    name: "Hà Nam",
    districts: [
      { id: "phu-ly", name: "Thành phố Phủ Lý" },
      { id: "duy-tien", name: "Thị xã Duy Tiên" },
      { id: "kim-bang", name: "Thị xã Kim Bảng" },
      { id: "thanh-liem", name: "Huyện Thanh Liêm" },
      { id: "ly-nhan", name: "Huyện Lý Nhân" },
    ],
  },
  {
    id: "ha-noi",
    name: "Hà Nội",
    districts: [
      { id: "ba-dinh", name: "Quận Ba Đình" },
      { id: "hoan-kiem", name: "Quận Hoàn Kiếm" },
      { id: "tay-ho", name: "Quận Tây Hồ" },
      { id: "cau-giay", name: "Quận Cầu Giấy" },
      { id: "dong-da", name: "Quận Đống Đa" },
      { id: "hai-ba-trung", name: "Quận Hai Bà Trưng" },
      { id: "thanh-xuan", name: "Quận Thanh Xuân" },
      { id: "ha-dong", name: "Quận Hà Đông" },
      { id: "cau-dien", name: "Quận Nam Từ Liêm" },
      { id: "long-bien", name: "Quận Long Biên" },
    ],
  },
  {
    id: "ha-tinh",
    name: "Hà Tĩnh",
    districts: [
      { id: "ha-tinh-city", name: "Thành phố Hà Tĩnh" },
      { id: "hong-linh", name: "Thị xã Hồng Lĩnh" },
      { id: "ky-anh-town", name: "Thị xã Kỳ Anh" },
      { id: "huong-son", name: "Huyện Hương Sơn" },
      { id: "cam-xuyen", name: "Huyện Cẩm Xuyên" },
      { id: "thach-ha", name: "Huyện Thạch Hà" },
    ],
  },
  {
    id: "hai-duong",
    name: "Hải Dương",
    districts: [
      { id: "hai-duong-city", name: "Thành phố Hải Dương" },
      { id: "chi-linh", name: "Thành phố Chí Linh" },
      { id: "kinh-mon", name: "Thị xã Kinh Môn" },
      { id: "gia-loc", name: "Huyện Gia Lộc" },
      { id: "nam-sach", name: "Huyện Nam Sách" },
      { id: "kim-thanh", name: "Huyện Kim Thành" },
    ],
  },
  {
    id: "hai-phong",
    name: "Hải Phòng",
    districts: [
      { id: "hong-bang", name: "Quận Hồng Bàng" },
      { id: "ngo-quyen", name: "Quận Ngô Quyền" },
      { id: "le-chan", name: "Quận Lê Chân" },
      { id: "hai-an", name: "Quận Hải An" },
      { id: "thuy-nguyen", name: "Huyện Thủy Nguyên" },
      { id: "an-duong", name: "Huyện An Dương" },
      { id: "do-son", name: "Quận Đồ Sơn" },
      { id: "cat-hai", name: "Huyện Cát Hải" },
    ],
  },
  {
    id: "hau-giang",
    name: "Hậu Giang",
    districts: [
      { id: "vi-thanh", name: "Thành phố Vị Thanh" },
      { id: "nga-bay", name: "Thành phố Ngã Bảy" },
      { id: "long-my-town", name: "Thị xã Long Mỹ" },
      { id: "phung-hiep", name: "Huyện Phụng Hiệp" },
      { id: "chau-thanh-a", name: "Huyện Châu Thành A" },
    ],
  },
  {
    id: "hoa-binh",
    name: "Hòa Bình",
    districts: [
      { id: "hoa-binh-city", name: "Thành phố Hòa Bình" },
      { id: "luong-son", name: "Huyện Lương Sơn" },
      { id: "kim-boi", name: "Huyện Kim Bôi" },
      { id: "mai-chau", name: "Huyện Mai Châu" },
      { id: "lac-thuy", name: "Huyện Lạc Thủy" },
    ],
  },
  {
    id: "hung-yen",
    name: "Hưng Yên",
    districts: [
      { id: "hung-yen-city", name: "Thành phố Hưng Yên" },
      { id: "my-hao", name: "Thị xã Mỹ Hào" },
      { id: "van-lam", name: "Huyện Văn Lâm" },
      { id: "yen-my", name: "Huyện Yên Mỹ" },
      { id: "khoai-chau", name: "Huyện Khoái Châu" },
    ],
  },
  {
    id: "khanh-hoa",
    name: "Khánh Hòa",
    districts: [
      { id: "nha-trang", name: "Thành phố Nha Trang" },
      { id: "cam-ranh", name: "Thành phố Cam Ranh" },
      { id: "ninh-hoa", name: "Thị xã Ninh Hòa" },
      { id: "van-ninh", name: "Huyện Vạn Ninh" },
      { id: "dien-khanh", name: "Huyện Diên Khánh" },
      { id: "truong-sa", name: "Huyện Trường Sa" },
    ],
  },
  {
    id: "kien-giang",
    name: "Kiên Giang",
    districts: [
      { id: "rach-gia", name: "Thành phố Rạch Giá" },
      { id: "ha-tien", name: "Thành phố Hà Tiên" },
      { id: "phu-quoc", name: "Thành phố Phú Quốc" },
      { id: "kien-luong", name: "Huyện Kiên Lương" },
      { id: "phu-quoc-dist", name: "Huyện Phú Quốc" },
      { id: "hon-dat", name: "Huyện Hòn Đất" },
    ],
  },
  {
    id: "kon-tum",
    name: "Kon Tum",
    districts: [
      { id: "kon-tum-city", name: "Thành phố Kon Tum" },
      { id: "dak-to", name: "Huyện Đắk Tô" },
      { id: "ngoc-hoi", name: "Huyện Ngọc Hồi" },
      { id: "sa-thay", name: "Huyện Sa Thầy" },
      { id: "kon-plong", name: "Huyện Kon Plông" },
    ],
  },
  {
    id: "lai-chau",
    name: "Lai Châu",
    districts: [
      { id: "lai-chau-city", name: "Thành phố Lai Châu" },
      { id: "phong-tho", name: "Huyện Phong Thổ" },
      { id: "sin-ho", name: "Huyện Sìn Hồ" },
      { id: "than-uyen", name: "Huyện Than Uyên" },
      { id: "muong-te", name: "Huyện Mường Tè" },
    ],
  },
  {
    id: "lam-dong",
    name: "Lâm Đồng",
    districts: [
      { id: "da-lat", name: "Thành phố Đà Lạt" },
      { id: "bao-loc", name: "Thành phố Bảo Lộc" },
      { id: "duc-trong", name: "Huyện Đức Trọng" },
      { id: "di-linh", name: "Huyện Di Linh" },
      { id: "lac-duong", name: "Huyện Lạc Dương" },
      { id: "don-duong", name: "Huyện Đơn Dương" },
    ],
  },
  {
    id: "lang-son",
    name: "Lạng Sơn",
    districts: [
      { id: "lang-son-city", name: "Thành phố Lạng Sơn" },
      { id: "chi-lang", name: "Huyện Chi Lăng" },
      { id: "huu-lung", name: "Huyện Hữu Lũng" },
      { id: "cao-loc", name: "Huyện Cao Lộc" },
      { id: "trang-dinh", name: "Huyện Tràng Định" },
    ],
  },
  {
    id: "lao-cai",
    name: "Lào Cai",
    districts: [
      { id: "lao-cai-city", name: "Thành phố Lào Cai" },
      { id: "sa-pa", name: "Thị xã Sa Pa" },
      { id: "bac-ha", name: "Huyện Bắc Hà" },
      { id: "bao-thang", name: "Huyện Bảo Thắng" },
      { id: "muong-khuong", name: "Huyện Mương Khương" },
    ],
  },
  {
    id: "long-an",
    name: "Long An",
    districts: [
      { id: "tan-an", name: "Thành phố Tân An" },
      { id: "kien-tuong", name: "Thị xã Kiến Tường" },
      { id: "duc-hoa", name: "Huyện Đức Hòa" },
      { id: "ben-luc", name: "Huyện Bến Lức" },
      { id: "can-guu", name: "Huyện Cần Giuộc" },
      { id: "chau-thanh-la", name: "Huyện Châu Thành" },
    ],
  },
  {
    id: "nam-dinh",
    name: "Nam Định",
    districts: [
      { id: "nam-dinh-city", name: "Thành phố Nam Định" },
      { id: "hai-hau", name: "Huyện Hải Hậu" },
      { id: "giao-thuy", name: "Huyện Giao Thủy" },
      { id: "y-yen", name: "Huyện Ý Yên" },
      { id: "xuan-truong", name: "Huyện Xuân Trường" },
      { id: "nghia-hung", name: "Huyện Nghĩa Hưng" },
    ],
  },
  {
    id: "nghe-an",
    name: "Nghệ An",
    districts: [
      { id: "vinh", name: "Thành phố Vinh" },
      { id: "cua-lo", name: "Thị xã Cửa Lò" },
      { id: "thai-hoa", name: "Thị xã Thái Hòa" },
      { id: "dien-chau", name: "Huyện Diễn Châu" },
      { id: "quynh-luu", name: "Huyện Quỳnh Lưu" },
      { id: "do-luong", name: "Huyện Đô Lương" },
    ],
  },
  {
    id: "ninh-binh",
    name: "Ninh Bình",
    districts: [
      { id: "ninh-binh-city", name: "Thành phố Ninh Bình" },
      { id: "tam-diep", name: "Thành phố Tam Điệp" },
      { id: "hoa-lu", name: "Huyện Hoa Lư" },
      { id: "kim-son", name: "Huyện Kim Sơn" },
      { id: "yen-khanh", name: "Huyện Yên Khánh" },
    ],
  },
  {
    id: "ninh-thuan",
    name: "Ninh Thuận",
    districts: [
      { id: "phan-rang", name: "Thành phố Phan Rang - Tháp Chàm" },
      { id: "ninh-son", name: "Huyện Ninh Sơn" },
      { id: "ninh-phuoc", name: "Huyện Ninh Phước" },
      { id: "thuan-bac", name: "Huyện Thuận Bắc" },
      { id: "ninh-hai", name: "Huyện Ninh Hải" },
    ],
  },
  {
    id: "phu-tho",
    name: "Phú Thọ",
    districts: [
      { id: "viet-tri", name: "Thành phố Việt Trì" },
      { id: "phu-tho-town", name: "Thị xã Phú Thọ" },
      { id: "lam-thao", name: "Huyện Lâm Thao" },
      { id: "thanh-son", name: "Huyện Thanh Sơn" },
      { id: "phu-ning", name: "Huyện Phù Ninh" },
    ],
  },
  {
    id: "phu-yen",
    name: "Phú Yên",
    districts: [
      { id: "tuy-hoa", name: "Thành phố Tuy Hòa" },
      { id: "song-cau", name: "Thị xã Sông Cầu" },
      { id: "dong-hoa", name: "Thị xã Đông Hòa" },
      { id: "tuy-an", name: "Huyện Tuy An" },
      { id: "tay-hoa", name: "Huyện Tây Hòa" },
    ],
  },
  {
    id: "quang-binh",
    name: "Quảng Bình",
    districts: [
      { id: "dong-hoi", name: "Thành phố Đồng Hới" },
      { id: "ba-don", name: "Thị xã Ba Đồn" },
      { id: "le-thuy", name: "Huyện Lệ Thủy" },
      { id: "quang-trach", name: "Huyện Quảng Trạch" },
      { id: "bo-trach", name: "Huyện Bố Trạch" },
    ],
  },
  {
    id: "quang-nam",
    name: "Quảng Nam",
    districts: [
      { id: "tam-ky", name: "Thành phố Tam Kỳ" },
      { id: "hoi-an", name: "Thành phố Hội An" },
      { id: "dien-ban", name: "Thị xã Điện Bàn" },
      { id: "nui-thanh", name: "Huyện Núi Thành" },
      { id: "dai-loc", name: "Huyện Đại Lộc" },
      { id: "thang-binh", name: "Huyện Thăng Bình" },
    ],
  },
  {
    id: "quang-ngai",
    name: "Quảng Ngãi",
    districts: [
      { id: "quang-ngai-city", name: "Thành phố Quảng Ngãi" },
      { id: "duc-pho", name: "Thị xã Đức Phổ" },
      { id: "binh-son", name: "Huyện Bình Sơn" },
      { id: "ly-son", name: "Huyện Lý Sơn" },
      { id: "tu-nghia", name: "Huyện Tư Nghĩa" },
    ],
  },
  {
    id: "quang-ninh",
    name: "Quảng Ninh",
    districts: [
      { id: "ha-long", name: "Thành phố Hạ Long" },
      { id: "mong-cai", name: "Thành phố Móng Cái" },
      { id: "cam-pha", name: "Thành phố Cẩm Phả" },
      { id: "uong-bi", name: "Thành phố Uông Bí" },
      { id: "dong-trieu", name: "Thành phố Đông Triều" },
      { id: "quang-yen", name: "Thị xã Quảng Yên" },
      { id: "van-don", name: "Huyện Vân Đồn" },
      { id: "co-to", name: "Huyện Cô Tô" },
    ],
  },
  {
    id: "quang-tri",
    name: "Quảng Trị",
    districts: [
      { id: "dong-ha", name: "Thành phố Đông Hà" },
      { id: "quang-tri-town", name: "Thị xã Quảng Trị" },
      { id: "gio-linh", name: "Huyện Gio Linh" },
      { id: "vinh-linh", name: "Huyện Vĩnh Linh" },
      { id: "trieu-phong", name: "Huyện Triệu Phong" },
      { id: "huong-hoa", name: "Huyện Hướng Hóa" },
    ],
  },
  {
    id: "soc-trang",
    name: "Sóc Trăng",
    districts: [
      { id: "soc-trang-city", name: "Thành phố Sóc Trăng" },
      { id: "vinh-chau", name: "Thị xã Vĩnh Châu" },
      { id: "nga-nam-town", name: "Thị xã Ngã Năm" },
      { id: "tran-de", name: "Huyện Trần Đề" },
      { id: "my-xuyen", name: "Huyện Mỹ Xuyên" },
    ],
  },
  {
    id: "son-la",
    name: "Sơn La",
    districts: [
      { id: "son-la-city", name: "Thành phố Sơn La" },
      { id: "moc-chau", name: "Huyện Mộc Châu" },
      { id: "mai-son", name: "Huyện Mai Sơn" },
      { id: "phu-yen-sl", name: "Huyện Phù Yên" },
      { id: "muong-la", name: "Huyện Mường La" },
    ],
  },
  {
    id: "tay-ninh",
    name: "Tây Ninh",
    districts: [
      { id: "tay-ninh-city", name: "Thành phố Tây Ninh" },
      { id: "trang-bang", name: "Thị xã Trảng Bàng" },
      { id: "hoa-thanh", name: "Thị xã Hòa Thành" },
      { id: "go-dau", name: "Huyện Gò Dầu" },
      { id: "duong-minh-chau", name: "Huyện Dương Minh Châu" },
    ],
  },
  {
    id: "thai-binh",
    name: "Thái Bình",
    districts: [
      { id: "thai-binh-city", name: "Thành phố Thái Bình" },
      { id: "dong-hung", name: "Huyện Đông Hưng" },
      { id: "quynh-phu", name: "Huyện Quỳnh Phụ" },
      { id: "tien-hai", name: "Huyện Tiền Hải" },
      { id: "thai-thuy", name: "Huyện Thái Thụy" },
    ],
  },
  {
    id: "thai-nguyen",
    name: "Thái Nguyên",
    districts: [
      { id: "thai-nguyen-city", name: "Thành phố Thái Nguyên" },
      { id: "song-cong", name: "Thành phố Sông Công" },
      { id: "pho-yen", name: "Thành phố Phổ Yên" },
      { id: "dai-tu", name: "Huyện Đại Từ" },
      { id: "phu-luong", name: "Huyện Phú Lương" },
    ],
  },
  {
    id: "thanh-hoa",
    name: "Thanh Hóa",
    districts: [
      { id: "thanh-hoa-city", name: "Thành phố Thanh Hóa" },
      { id: "sam-son", name: "Thành phố Sầm Sơn" },
      { id: "bim-son", name: "Thị xã Bỉm Sơn" },
      { id: "nghi-son", name: "Thị xã Nghi Sơn" },
      { id: "dong-son", name: "Huyện Đông Sơn" },
      { id: "quang-xuong", name: "Huyện Quảng Xương" },
    ],
  },
  {
    id: "thua-thien-hue",
    name: "Thừa Thiên Huế",
    districts: [
      { id: "hue", name: "Thành phố Huế" },
      { id: "huong-thuy", name: "Thị xã Hương Thủy" },
      { id: "huong-tra", name: "Thị xã Hương Trà" },
      { id: "phu-loc", name: "Huyện Phú Lộc" },
      { id: "phong-dien-tth", name: "Huyện Phong Điền" },
      { id: "quang-dien", name: "Huyện Quảng Điền" },
    ],
  },
  {
    id: "tien-giang",
    name: "Tiền Giang",
    districts: [
      { id: "my-tho", name: "Thành phố Mỹ Tho" },
      { id: "go-cong-town", name: "Thị xã Gò Công" },
      { id: "cai-lay-town", name: "Thị xã Cai Lậy" },
      { id: "chau-thanh-tg", name: "Huyện Châu Thành" },
      { id: "cho-gao", name: "Huyện Chợ Gạo" },
    ],
  },
  {
    id: "tp-ho-chi-minh",
    name: "Thành phố Hồ Chí Minh",
    districts: [
      { id: "quan-1", name: "Quận 1" },
      { id: "quan-2", name: "Quận 2" },
      { id: "quan-3", name: "Quận 3" },
      { id: "quan-4", name: "Quận 4" },
      { id: "quan-5", name: "Quận 5" },
      { id: "quan-6", name: "Quận 6" },
      { id: "quan-7", name: "Quận 7" },
      { id: "quan-8", name: "Quận 8" },
      { id: "quan-10", name: "Quận 10" },
      { id: "quan-11", name: "Quận 11" },
      { id: "quan-12", name: "Quận 12" },
      { id: "thu-duc", name: "Thành phố Thủ Đức" },
      { id: "binh-thanh", name: "Quận Bình Thạnh" },
      { id: "go-vap", name: "Quận Gò Vấp" },
      { id: "tan-binh", name: "Quận Tân Bình" },
      { id: "tan-phu", name: "Quận Tân Phú" },
      { id: "binh-tan", name: "Quận Bình Tân" },
      { id: "binh-chanh", name: "Huyện Bình Chánh" },
      { id: "hoc-mon", name: "Huyện Hóc Môn" },
      { id: "cu-chi", name: "Huyện Củ Chi" },
      { id: "nha-be", name: "Huyện Nhà Bè" },
      { id: "can-gio", name: "Huyện Cần Giờ" },
    ],
  },
  {
    id: "tra-vinh",
    name: "Trà Vinh",
    districts: [
      { id: "tra-vinh-city", name: "Thành phố Trà Vinh" },
      { id: "duyen-hai-town", name: "Thị xã Duyên Hải" },
      { id: "cau-ngang", name: "Huyện Cầu Ngang" },
      { id: "tieu-can", name: "Huyện Tiểu Cần" },
      { id: "cang-long", name: "Huyện Càng Long" },
    ],
  },
  {
    id: "tuyen-quang",
    name: "Tuyên Quang",
    districts: [
      { id: "tuyen-quang-city", name: "Thành phố Tuyên Quang" },
      { id: "son-duong", name: "Huyện Sơn Dương" },
      { id: "yen-son", name: "Huyện Yên Sơn" },
      { id: "chiem-hoa", name: "Huyện Chiêm Hóa" },
      { id: "ham-yen", name: "Huyện Hàm Yên" },
    ],
  },
  {
    id: "vinh-long",
    name: "Vĩnh Long",
    districts: [
      { id: "vinh-long-city", name: "Thành phố Vĩnh Long" },
      { id: "binh-minh", name: "Thị xã Bình Minh" },
      { id: "long-ho", name: "Huyện Long Hồ" },
      { id: "mang-thit", name: "Huyện Mang Thít" },
      { id: "vung-liem", name: "Huyện Vũng Liêm" },
    ],
  },
  {
    id: "vinh-phuc",
    name: "Vĩnh Phúc",
    districts: [
      { id: "vinh-yen", name: "Thành phố Vĩnh Yên" },
      { id: "phuc-yen", name: "Thành phố Phúc Yên" },
      { id: "binh-xuyen", name: "Huyện Bình Xuyên" },
      { id: "vinh-tuong", name: "Huyện Vĩnh Tường" },
      { id: "yen-lac", name: "Huyện Yên Lạc" },
    ],
  },
  {
    id: "yen-bai",
    name: "Yên Bái",
    districts: [
      { id: "yen-bai-city", name: "Thành phố Yên Bái" },
      { id: "nghia-lo", name: "Thị xã Nghĩa Lộ" },
      { id: "luc-yen", name: "Huyện Lục Yên" },
      { id: "van-yen", name: "Huyện Văn Yên" },
      { id: "tran-yen", name: "Huyện Trấn Yên" },
    ],
  },
];
